Remove deprecated RouteObjectInterface, PHP8.1 compatibility.
coldfrontlabs/drupal-codeception pull request #4
Opened 2023-06-08 07:49 UTC by adubovskoy

2023-06-13 10:33 UTC, minorOffense requested changes

2023-06-13 10:33 UTC, minorOffense commented on src/Codeception/Module/DrupalUser.php
> +    var_dump($user->getAccountName());
Is this some debug left in?

2023-06-13 10:33 UTC, minorOffense commented on src/Codeception/Module/DrupalUser.php
> +        $output = Drush::runDrush($alias. '--uri=' . $this->_getConfig('site') . ' uli --name=' . $username, $this->_getConfig('drush'), $this->_getConfig('working_directory'));
Is this to add support for multisite?

2023-06-19 13:34 UTC, adubovskoy commented on src/Codeception/Module/DrupalUser.php
> +        $output = Drush::runDrush($alias. '--uri=' . $this->_getConfig('site') . ' uli --name=' . $username, $this->_getConfig('drush'), $this->_getConfig('working_directory'));
Yes, correct.

2023-06-19 13:34 UTC, adubovskoy commented on src/Codeception/Module/DrupalUser.php
> +    var_dump($user->getAccountName());
Ohh, thank you for noticing that!

2023-06-19 13:35 UTC, adubovskoy reviewed
Remove debug string.

2023-06-20 13:51 UTC, minorOffense approved these changes

2023-06-20 13:51 UTC, merged